spring.application.name=PawnPrime
# PostgreSQL DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/pawn
spring.datasource.username=postgres
spring.datasource.password=root
 
# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver
 
# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
 
spring.security.user.name=admin
spring.security.user.password=admin
jwt.secret=feSi0svNpOGVwm4zSBDNlstzqEIhKcFFyqrlsIZHhq2hyf
jwt.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bhuvantinani@gmail.com
spring.mail.password=yzrz bkzj gaal zidt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud_name=dzymiayhf
cloudinary.api_key=238234398964623
cloudinary.api_secret=90xlI3SDVy1G5f5hLTgw-rJQFSU

razorpay.key.id=rzp_test_RLw8vN0YJLRwR1
razorpay.key.secret=UIAi30q29PeWXWpKrQYybB5m

